{"id": "a6b4d691-cbb8-4acb-b17b-d158372dae08", "stack_trace": "Traceback (most recent call last):\n  File \"tests.py\", line 34, in _run_failure_code\n    self._fail()\n  File \"tests.py\", line 27, in _fail\n    y = 5 / 0\nZeroDivisionError: division by zero\n", "error_type": "<class 'ZeroDivisionError'>", "timestamp": "2020-08-18 20:02:08.945872"}
{"id": "ad52be5b-55bd-4fdb-b5a5-0c45df7bfd68", "stack_trace": "Traceback (most recent call last):\n  File \"tests.py\", line 34, in _run_failure_code\n    self._fail()\n  File \"tests.py\", line 27, in _fail\n    y = 5 / 0\nZeroDivisionError: division by zero\n", "error_type": "<class 'ZeroDivisionError'>", "timestamp": "2020-08-18 20:03:47.072936"}
{"id": "023c6e7f-71b8-4a42-a137-01600976305a", "stack_trace": "Traceback (most recent call last):\n  File \"tests.py\", line 34, in _run_failure_code\n    self._fail()\n  File \"tests.py\", line 27, in _fail\n    y = 5 / 0\nZeroDivisionError: division by zero\n", "error_type": "<class 'ZeroDivisionError'>", "timestamp": "2020-08-30 13:38:06.445140"}
{"id": "85067d95-b793-4da6-a7ef-f313fe87d4b3", "stack_trace": "NoneType: None\n", "error_type": "<class 'type'>", "timestamp": "2020-08-30 14:00:21.976930"}
{"id": "c132d059-0602-4ca5-a271-a42b9b92757e", "stack_trace": null, "error_type": "<class 'type'>", "timestamp": "2020-08-30 14:04:18.414951"}
{"id": "5d4289b3-0192-4c4b-9e86-9a3588fa3b88", "stack_trace": ["  File \"failtest.py\", line 10, in <module>\n    raise NannyTestError\n"], "error_type": "<class 'type'>", "timestamp": "2020-08-30 14:08:00.614458"}
{"id": "9819ebf1-4b9c-4564-8d6d-54a5ddcfa499", "stack_trace": ["  File \"failtest.py\", line 10, in <module>\n    raise NannyTestError\n"], "error_type": "<class '__main__.NannyTestError'>", "timestamp": "2020-08-30 14:08:52.337815"}
{"id": "97666bcb-639f-460c-b804-ebb83dffef58", "stack_trace": ["  File \"nanny.py\", line 51, in <module>\n    init()\n", "  File \"nanny.py\", line 47, in init\n    subprocess.run([\"python3\", parser.parse_args()])\n", "  File \"/usr/lib/python3.6/subprocess.py\", line 423, in run\n    with Popen(*popenargs, **kwargs) as process:\n", "  File \"/usr/lib/python3.6/subprocess.py\", line 729, in __init__\n    restore_signals, start_new_session)\n", "  File \"/usr/lib/python3.6/subprocess.py\", line 1295, in _execute_child\n    restore_signals, start_new_session, preexec_fn)\n"], "error_type": "<class 'TypeError'>", "timestamp": "2020-08-30 20:53:27.441829"}
{"id": "12321664-b096-4599-81bd-f4d9f52d8e34", "stack_trace": ["  File \"<stdin>\", line 1, in <module>\n"], "error_type": "<class 'NameError'>", "timestamp": "2020-10-16 15:52:18.681442"}
{"id": "3833bdee-48ed-4deb-904d-350d4c511fd2", "stack_trace": ["  File \"<stdin>\", line 1, in <module>\n"], "error_type": "<class 'Exception'>", "timestamp": "2020-10-16 15:55:49.979439"}
{"id": "6756c11c-e892-49fe-83c9-b2c97820bf85", "stack_trace": ["  File \"failtest.py\", line 14, in <module>\n    raise NannyTestError\n"], "error_type": "<class '__main__.NannyTestError'>", "timestamp": "2020-10-16 16:08:45.060886"}
{"id": "517ab02c-a205-4121-b496-d87c4e8cb017", "stack_trace": ["  File \"failtest.py\", line 14, in <module>\n    raise NannyTestError\n"], "error_type": "<class '__main__.NannyTestError'>", "timestamp": "2020-10-16 16:10:03.565878"}
{"id": "3f608ba1-8c59-488d-8270-3310f9ea75f1", "stack_trace": ["  File \"failtest.py\", line 14, in <module>\n    raise NannyTestError\n"], "error_type": "<class '__main__.NannyTestError'>", "timestamp": "2020-10-16 16:11:02.685404"}
{"id": "a6f3f629-af4c-4490-b691-c7ce694fdbd8", "stack_trace": ["  File \"failtest.py\", line 14, in <module>\n    raise NannyTestError\n"], "error_type": "<class '__main__.NannyTestError'>", "timestamp": "2020-10-16 16:16:55.092589"}
{"id": "46db259f-ae0c-4030-9448-707a6ad61ba1", "stack_trace": ["  File \"failtest.py\", line 14, in <module>\n    raise NannyTestError\n"], "error_type": "<class '__main__.NannyTestError'>", "timestamp": "2020-10-16 16:30:41.365705"}
{"id": "cdf5a965-7039-4ed8-8b7e-bef9e38a5a8a", "stack_trace": ["  File \"failtest.py\", line 14, in <module>\n    raise NannyTestError\n"], "error_type": "<class '__main__.NannyTestError'>", "timestamp": "2020-10-16 16:32:19.149336"}
{"id": "e724c1c8-71a0-42c1-aee2-d1db609fd331", "stack_trace": ["  File \"failtest.py\", line 14, in <module>\n    raise NannyTestError\n"], "error_type": "<class '__main__.NannyTestError'>", "timestamp": "2020-10-16 16:33:27.406961"}
{"id": "6a71d216-150d-4e1e-8c69-4f193f846998", "stack_trace": ["  File \"failtest.py\", line 14, in <module>\n    raise NannyTestError\n"], "error_type": "<class '__main__.NannyTestError'>", "timestamp": "2020-10-16 16:34:36.522093"}
{"id": "aee6b622-7654-451f-a567-ccdd2baa6806", "stack_trace": ["  File \"failtest.py\", line 14, in <module>\n    raise NannyTestError\n"], "error_type": "<class '__main__.NannyTestError'>", "timestamp": "2020-10-16 16:35:07.118120"}
{"id": "dfcc104e-6806-4e94-a82c-841f5b73ce70", "stack_trace": ["  File \"failtest.py\", line 14, in <module>\n    raise NannyTestError\n"], "error_type": "<class '__main__.NannyTestError'>", "timestamp": "2020-10-16 16:35:15.836154"}
{"id": "6e099ee5-18ae-4539-bb49-d4381aef1e9d", "stack_trace": ["  File \"failtest.py\", line 14, in <module>\n    raise NannyTestError\n"], "error_type": "<class '__main__.NannyTestError'>", "timestamp": "2020-10-16 16:38:02.223875"}
{"id": "ff473101-c7b9-4aa4-b384-dc0b96f49dcf", "stack_trace": ["  File \"failtest.py\", line 14, in <module>\n    raise NannyTestError\n"], "error_type": "<class '__main__.NannyTestError'>", "timestamp": "2020-10-16 16:44:11.572966"}
{"id": "5a8fec4b-0d5b-49a5-8cba-acde3b14b0a9", "stack_trace": ["  File \"failtest.py\", line 14, in <module>\n    raise NannyTestError\n"], "error_type": "<class '__main__.NannyTestError'>", "timestamp": "2020-10-16 16:44:36.963022"}
